/*
 * AMRIT – Accessible Medical Records via Integrated Technology
 * Integrated EHR (Electronic Health Records) Solution
 *
 * Copyright (C) "Piramal Swasthya Management and Research Institute"
 *
 * This file is part of AMRIT.
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see https://www.gnu.org/licenses/.
 */
import { Injectable } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { Observable } from 'rxjs';
import { environment } from 'src/environments/environment';

/** Beneficiary/consent details the CN sends from /init onward. */
export interface OnhsPatientDetails {
  patientId: string;
  patientName: string;
  abhaId: string;
  dateOfBirth: string;
  gender: string;
  primaryLanguage: string;
  flwId: string;
  flwName: string;
  chwId: string;
  clientNotes: string;
}

/** The resource/offer pair a commitment is built on. */
export interface OnhsSelection {
  resourceId: string;
  offerId: string;
}

@Injectable()
export class OnhsService {
  /** One transaction id correlates the whole discover -> status ladder. */
  transactionId = '';

  /** Assigned by the provider node at on_select; needed by init/confirm/status. */
  contractId = '';

  /** Re-priced by the provider at on_select; falls back to the catalog default. */
  considerationId = environment.onhsConsiderationId;

  /** Quoted amount and currency for the chosen offer. */
  amount = 250;
  currency = 'INR';

  /**
   * The provider node this booking is routed to, from /select onward. Beckn
   * requires these to identify the provider that published the chosen offer, so
   * they are taken from that offer's catalog rather than being fixed — the
   * network carries several providers, each on its own bppUri. The configured
   * values are only a fallback for a catalog that omits them.
   */
  bppId = environment.onhsBppId;
  bppUri = environment.onhsBppUri;

  /** Points subsequent calls at the provider that published the chosen offer. */
  setProvider(bppId: string, bppUri: string): void {
    this.bppId = bppId || environment.onhsBppId;
    this.bppUri = bppUri || environment.onhsBppUri;
  }

  /** Payment method the payer chose on the payment screen. */
  paymentMethod = 'UPI';

  /**
   * Reference to pre-purchased capacity (a UC0 HealthEntitlement). A
   * consideration must carry exactly one funding path, so when this is set the
   * fresh paymentAuthorisation is omitted and the engagement draws down the
   * entitlement instead.
   */
  entitlementRef = '';

  /**
   * TEST MODE. No payment gateway is called and no money moves. The
   * authorisation below is generated locally so the protocol has a well-formed
   * paymentAuthorisation to carry at /confirm. Replace this with a real gateway
   * response before any live use.
   */
  readonly testPaymentMode = true;

  /** Reference generated by the last simulated authorisation. */
  lastPaymentRef = '';
  lastAuthCode = '';

  private readonly base = environment.onhsSeekerBase || '';

  constructor(private http: HttpClient) {
    this.newTransaction();
  }

  /** Mints a fresh session id and clears everything the provider assigns. */
  newTransaction(): string {
    this.transactionId = OnhsService.uuid();
    this.contractId = '';
    this.considerationId = environment.onhsConsiderationId;
    this.bppId = environment.onhsBppId;
    this.bppUri = environment.onhsBppUri;
    this.lastPaymentRef = '';
    this.lastAuthCode = '';
    this.entitlementRef = '';
    return this.transactionId;
  }

  /** RFC 4122 v4 id, with a fallback for browsers without crypto.randomUUID. */
  static uuid(): string {
    const cryptoRef: any = typeof crypto !== 'undefined' ? crypto : undefined;
    if (cryptoRef?.randomUUID) {
      return cryptoRef.randomUUID();
    }
    if (cryptoRef?.getRandomValues) {
      const buf = new Uint8Array(16);
      cryptoRef.getRandomValues(buf);
      buf[6] = (buf[6] & 0x0f) | 0x40;
      buf[8] = (buf[8] & 0x3f) | 0x80;
      const hex = Array.from(buf, (b: number) =>
        b.toString(16).padStart(2, '0'),
      ).join('');
      return `${hex.slice(0, 8)}-${hex.slice(8, 12)}-${hex.slice(
        12,
        16,
      )}-${hex.slice(16, 20)}-${hex.slice(20)}`;
    }
    return 'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'.replace(/[xy]/g, (c) => {
      const r = (Math.random() * 16) | 0;
      const v = c === 'x' ? r : (r & 0x3) | 0x8;
      return v.toString(16);
    });
  }

  /**
   * Beckn core Context. bppId/bppUri identify the provider node and are only
   * sent from /select onward; /discover fans out across the network instead.
   */
  private buildContext(
    action: string,
    schemaContext: string[],
    withBpp: boolean,
  ) {
    const context: any = {
      domain: environment.onhsDomain,
      networkId: environment.onhsNetworkId,
      action,
      version: environment.onhsVersion,
      bapId: environment.onhsBapId,
      bapUri: environment.onhsBapUri,
      transactionId: this.transactionId,
      messageId: OnhsService.uuid(),
      timestamp: new Date().toISOString(),
      ttl: environment.onhsTtl,
      schemaContext,
    };
    if (withBpp) {
      context.bppId = this.bppId;
      context.bppUri = this.bppUri;
    }
    return context;
  }

  private post(action: string, body: any): Observable<any> {
    return this.http.post(`${this.base}/bap/caller/${action}`, body);
  }

  /**
   * Every POST returns only an ACK. The real answer arrives asynchronously as an
   * /on_* callback, which the seeker sandbox parks until this long-poll picks it
   * up. A timeout comes back as HTTP 404 with an `error` field.
   */
  waitForCallback(action: string): Observable<any> {
    const timeout = environment.onhsCallbackTimeout;
    return this.http.get(
      `${this.base}/seeker/api/callbacks/${this.transactionId}/wait/${action}?timeout=${timeout}`,
    );
  }

  /** Step 1 - "what's available?" Intent only, no contract and no PII. */
  discover(searchText: string): Observable<any> {
    return this.post('discover', {
      context: this.buildContext(
        'discover',
        [
          'https://schema.beckn.io/HealthResource/v2.1/context.jsonld',
          'https://schema.beckn.io/HealthOffer/v2.1/context.jsonld',
          'https://schema.beckn.io/HealthConsideration/v2.1/context.jsonld',
        ],
        false,
      ),
      message: { intent: { textSearch: searchText } },
    });
  }

  /** Step 2 - "quote me this exact thing." Ids only; PII is not allowed here. */
  select(selection: OnhsSelection): Observable<any> {
    return this.post('select', {
      context: this.buildContext(
        'select',
        [
          'https://schema.beckn.io/HealthResource/v2.1/context.jsonld',
          'https://schema.beckn.io/HealthOffer/v2.1/context.jsonld',
        ],
        true,
      ),
      message: {
        contract: {
          commitments: [this.buildCommitment(selection, 'DRAFT')],
        },
      },
    });
  }

  /** Step 3 - "here's who it's for, how do I pay?" First call carrying PII. */
  init(selection: OnhsSelection, patient: OnhsPatientDetails): Observable<any> {
    return this.post('init', {
      context: this.buildContext(
        'init',
        [
          'https://schema.beckn.io/HealthConsideration/v2.1/context.jsonld',
          'https://schema.beckn.io/HealthContract/v2.1/context.jsonld',
          'https://schema.beckn.io/HealthParticipant/v2.1/context.jsonld',
        ],
        true,
      ),
      message: {
        contract: {
          ...this.contractIdFragment(),
          descriptor: this.buildDescriptor(patient),
          commitments: [this.buildCommitment(selection, 'DRAFT')],
          consideration: [this.buildConsideration('QUOTED', false)],
          participants: this.buildParticipants(patient),
          contractAttributes: this.buildContractAttributes(patient),
        },
      },
    });
  }

  /** Step 4 - "here's proof, make it real." Carries the payment authorisation. */
  confirm(
    selection: OnhsSelection,
    patient: OnhsPatientDetails,
  ): Observable<any> {
    return this.post('confirm', {
      context: this.buildContext(
        'confirm',
        [
          'https://schema.beckn.io/HealthConsideration/v2.1/context.jsonld',
          'https://schema.beckn.io/HealthContract/v2.1/context.jsonld',
          'https://schema.beckn.io/HealthParticipant/v2.1/context.jsonld',
          'https://schema.beckn.io/HealthSettlement/v2.1/context.jsonld',
        ],
        true,
      ),
      message: {
        contract: {
          ...this.contractIdFragment(),
          descriptor: this.buildDescriptor(patient),
          commitments: [this.buildCommitment(selection, 'ACTIVE')],
          consideration: [this.buildConsideration('AUTHORISED', true)],
          participants: this.buildParticipants(patient),
          contractAttributes: this.buildContractAttributes(patient),
          settlements: [
            {
              id: 'SETTLE-001',
              considerationId: this.considerationId,
              status: 'COMMITTED',
              settlementAttributes: {
                '@context':
                  'https://schema.beckn.io/HealthSettlement/v2.1/context.jsonld',
                '@type': 'hst:HealthSettlement',
                paymentNotes: 'UPI payment authorised by seeker',
              },
            },
          ],
        },
      },
    });
  }

  /** Step 5 - "what happened / what's the result?" Polls by contract id. */
  status(selection: OnhsSelection): Observable<any> {
    return this.post('status', {
      context: this.buildContext(
        'status',
        [
          'https://schema.beckn.io/HealthContract/v2.1/context.jsonld',
          'https://schema.beckn.io/HealthPerformance/v2.1/context.jsonld',
          'https://schema.beckn.io/HealthSettlement/v2.1/context.jsonld',
          'https://schema.beckn.io/HealthConsideration/v2.1/context.jsonld',
          'https://schema.beckn.io/HealthParticipant/v2.1/context.jsonld',
        ],
        true,
      ),
      message: {
        contract: {
          id: this.contractId,
          commitments: [this.buildCommitment(selection, 'ACTIVE')],
        },
      },
    });
  }

  /** Seeker-side view of which callbacks have landed for this transaction. */
  getFlow(): Observable<any> {
    return this.http.get(`${this.base}/seeker/api/flow/${this.transactionId}`);
  }

  /** Every raw callback stored against this transaction. */
  getAllCallbacks(): Observable<any> {
    return this.http.get(
      `${this.base}/seeker/api/callbacks/${this.transactionId}`,
    );
  }

  /**
   * Beckn marks contract.id optional at init/confirm (echo it only if the
   * provider already assigned one) and mandatory at status. Sending an empty
   * string would be rejected, so the key is omitted until it exists.
   */
  private contractIdFragment(): { id?: string } {
    return this.contractId ? { id: this.contractId } : {};
  }

  private buildCommitment(selection: OnhsSelection, code: string) {
    return {
      id: 'commitment-uc1-001',
      status: { descriptor: { code } },
      resources: [{ id: selection.resourceId, quantity: { count: 1 } }],
      offer: {
        id: selection.offerId,
        resourceIds: [selection.resourceId],
      },
    };
  }

  /**
   * At confirm the consideration must carry exactly one funding path. This demo
   * is UC1 pay-at-counter, so it sends a fresh paymentAuthorisation and never an
   * entitlementRef.
   */
  private buildConsideration(statusCode: string, authorised: boolean) {
    const attributes: any = {
      '@context':
        'https://schema.beckn.io/HealthConsideration/v2.1/context.jsonld',
      '@type': 'hcn:HealthConsideration',
      pricePerUnit: this.amount,
      currency: this.currency,
      totalAmount: this.amount,
      netAmount: this.amount,
      payerArchetype: 'SELF',
      paymentMethodsAccepted: ['UPI', 'BANK_TRANSFER', 'CASH_VIA_FLW'],
      selectedPaymentMethod: this.paymentMethod,
    };
    if (authorised) {
      if (this.entitlementRef) {
        // Entitlement drawdown: no fresh payment accompanies this engagement.
        attributes.entitlementRef = this.entitlementRef;
        attributes.payerArchetype = 'INSTITUTIONAL';
        this.lastPaymentRef = this.entitlementRef;
        this.lastAuthCode = '';
      } else {
        // Simulated authorisation - see testPaymentMode.
        this.lastPaymentRef = `TEST-${this.paymentMethod}-${Date.now()}`;
        this.lastAuthCode = `TEST-AUTH-${Math.floor(
          1000 + Math.random() * 9000,
        )}`;
        attributes.transactionRef = this.lastPaymentRef;
        attributes.paymentAuthorisation = {
          authCode: this.lastAuthCode,
          authProvider: 'TEST-GATEWAY',
          authTimestamp: new Date().toISOString(),
          authAmount: attributes.netAmount,
        };
      }
    }
    return {
      id: this.considerationId,
      status: { code: statusCode },
      considerationAttributes: attributes,
    };
  }

  /** Consent PDFs and cough audio travel as document references, never inline. */
  private buildDescriptor(patient: OnhsPatientDetails) {
    return {
      name: `VKS AI Cough Analysis - ${patient.patientName}`,
      docs: [
        {
          label: 'CONSENT-DOC-001',
          url: `${environment.onhsBapUri.replace(
            '/bap/receiver',
            '',
          )}/seeker/artifacts/consent.pdf`,
          mimeType: 'application/pdf',
          standard: 'HealthConsent/v1',
        },
        ...this.audioLabels().map((label, i) => ({
          label,
          url: `https://example.com/cough-${i + 1}.wav`,
          mimeType: 'audio/wav',
        })),
      ],
    };
  }

  private audioLabels(): string[] {
    return ['COUGH-AUDIO-001', 'COUGH-AUDIO-002', 'COUGH-AUDIO-003'];
  }

  private buildParticipants(patient: OnhsPatientDetails) {
    /*
     * dateOfBirth is schema-validated as a `date` (YYYY-MM-DD). An empty string
     * fails that pattern and the network rejects the whole init with
     * "string doesn't match the format date", so omit the key when unset
     * rather than sending a blank. Optional-but-absent is accepted; blank is
     * not. Blank healthIds values are tolerated, so those are left as they are.
     */
    const dob = (patient.dateOfBirth || '').trim();
    const patientAttributes: any = {
      '@context':
        'https://schema.beckn.io/HealthParticipant/v2.1/context.jsonld',
      '@type': 'hpa:HealthParticipant',
      participantRole: 'PATIENT',
      healthIds: [{ system: 'ABHA', value: patient.abhaId }],
      gender: patient.gender,
      primaryLanguage: patient.primaryLanguage,
    };
    if (dob) {
      patientAttributes.dateOfBirth = dob;
    }

    return [
      {
        id: patient.patientId,
        descriptor: { name: patient.patientName },
        participantAttributes: patientAttributes,
      },
      {
        id: patient.flwId,
        descriptor: { name: patient.flwName },
        participantAttributes: {
          '@context':
            'https://schema.beckn.io/HealthParticipant/v2.1/context.jsonld',
          '@type': 'hpa:HealthParticipant',
          participantRole: 'FIELD_WORKER',
          healthIds: [{ system: 'CHW-ID', value: patient.chwId }],
          primaryLanguage: patient.primaryLanguage,
        },
      },
    ];
  }

  /**
   * ONHS network policy requires consent and inputArtifacts whenever
   * healthServiceType is DIAGNOSTIC_ANALYTICS.
   */
  private buildContractAttributes(patient: OnhsPatientDetails) {
    return {
      '@context': 'https://schema.beckn.io/HealthContract/v2.1/context.jsonld',
      '@type': 'hct:HealthContract',
      healthServiceType: 'DIAGNOSTIC_ANALYTICS',
      bookingChannel: 'APP',
      facilitatorId: patient.flwId,
      clientNotes: patient.clientNotes,
      inputArtifacts: this.audioLabels().map((label) => ({
        artifactRef: label,
        artifactType: 'AUDIO_SAMPLE',
        mimeType: 'audio/wav',
        revocationStatus: 'ACTIVE',
      })),
      consent: {
        consentDocRef: 'CONSENT-DOC-001',
        consentId: OnhsService.uuid(),
        consentStandard: 'HealthConsent/v1',
        consentedAt: new Date().toISOString(),
        purposeOfCollection: ['DIAGNOSTIC', 'QUALITY_ASSURANCE'],
        patientParticipantId: patient.patientId,
        consentedBy: patient.flwId,
        dataRetentionDays: 90,
      },
    };
  }
}
